# Generated by Django 5.1 on 2024-08-13 00:40

import usersApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pendingUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20, verbose_name='Username')),
                ('last_name', models.CharField(max_length=20)),
                ('contact_info', models.CharField(max_length=11, unique=True, validators=[usersApp.models.contactVal])),
            ],
        ),
    ]
