# Generated by Django 5.1 on 2024-08-13 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendinguser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
