# Generated by Django 5.1 on 2024-08-18 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersApp', '0002_pendinguser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendinguser',
            name='first_name',
            field=models.CharField(max_length=20, verbose_name='First_name'),
        ),
    ]
