# Generated by Django 5.1 on 2024-08-19 12:21

import usersApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersApp', '0004_alter_pendinguser_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='pendingUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20, verbose_name='username')),
                ('last_name', models.CharField(max_length=20)),
                ('contact_info', models.CharField(max_length=11, unique=True, validators=[usersApp.models.contactVal])),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=15, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='pendingUser',
        ),
    ]
