# Generated by Django 5.1 on 2024-09-04 22:47

import django.db.models.deletion
import usersApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersApp', '0006_assignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='pendingUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20, verbose_name='username')),
                ('last_name', models.CharField(max_length=20)),
                ('contact_info', models.CharField(max_length=11, unique=True, validators=[usersApp.models.contactVal])),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=15, unique=True)),
                ('time_registered', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='assignment',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usersApp.pendinguser'),
        ),
        migrations.DeleteModel(
            name='pendingUsers',
        ),
    ]
