# Generated by Django 5.1 on 2024-09-04 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usersApp', '0007_pendinguser_alter_assignment_created_by_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='assignment',
            new_name='assign',
        ),
    ]
