# Generated by Django 5.1 on 2024-09-04 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usersApp', '0008_rename_assignment_assign'),
    ]

    operations = [
        migrations.DeleteModel(
            name='assign',
        ),
    ]
