# Generated by Django 5.1 on 2024-09-05 22:44

import usersApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersApp', '0010_daily_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendinguser',
            name='contact_info',
            field=models.CharField(max_length=11, validators=[usersApp.models.contactVal]),
        ),
    ]
