# Generated by Django 5.1 on 2024-09-07 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usersApp', '0011_alter_pendinguser_contact_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pendinguser',
            name='contact_info',
        ),
    ]
