# Generated by Django 5.1 on 2024-09-14 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usersApp', '0014_alter_daily_task_created_by_delete_pendinguser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='daily_task',
            old_name='created',
            new_name='created_at',
        ),
    ]
