# Generated by Django 5.1 on 2024-09-22 16:34

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usersApp', '0015_rename_created_daily_task_created_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='daily_task',
            new_name='daily_tasks',
        ),
    ]
