# Generated by Django 5.1 on 2024-09-22 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usersApp', '0016_rename_daily_task_daily_tasks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='daily_tasks',
            old_name='created_at',
            new_name='create_at',
        ),
        migrations.RenameField(
            model_name='daily_tasks',
            old_name='created_by',
            new_name='create_by',
        ),
    ]
