# Generated by Django 5.1 on 2024-09-22 16:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usersApp', '0017_rename_created_at_daily_tasks_create_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='daily_tasks',
            new_name='daily_task',
        ),
        migrations.RenameField(
            model_name='daily_task',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='daily_task',
            old_name='create_by',
            new_name='created_by',
        ),
    ]
